### ISSUE TITLE
Storage Retrievals - Switch to public IPFS gateways (Filebase or Cloudflare)

### ISSUE THREAD

**Issue by jaybuidl** [kleros/builder-baseline#11]
```[tasklist]
### Tasks
- [ ] https://github.com/kleros/court/pull/410
- [x] Court v2
- [x] Escrow v1
- [x] Escrow v2
- [ ] https://github.com/kleros/gtcr/issues/333
- [x] Curate v2
- [x] Proof of Humanity v1
- [x] Proof of Humanity v2
- [x] Dispute Resolver v1
- [x] PNK Merkle Drop
- [ ] Moderate
```

**Comment by salgozino** [comment]
PoH-V2 still pointing to kleros ipfs endpoint: https://github.com/Proof-Of-Humanity/proof-of-humanity-v2-web/blob/ce045ce689e4a2dc5bbe29c36508dfeeab7fc69b/src/utils/ipfs.ts#L8

issue to track this change: https://github.com/Proof-Of-Humanity/proof-of-humanity-v2-web/issues/32

**Comment by salgozino** [comment]
Curate-v2 has defined an envvar IPFS_GATEWAY to use, and by default is using cdn.kleros.io ✅.
There are a few of hardcoded values pointing to ipfs.kleros.io that should be changed. I've created the issue to track those changes.
https://github.com/kleros/curate-v2/issues/19
