### ISSUE TITLE
Storage Uploads - Switch to the Filebase/IPFS pipeline

### ISSUE THREAD

**Issue by jaybuidl** [kleros/builder-baseline#12]
Notes by @Harman-singh-waraich: https://hackmd.io/@-cmxt73kRVi2uFMhhabm4A/S1C0x_pNA

```[tasklist]
### Tasks
- [x] Court v1: nothing to do
- [x] Court v2
- [x] Escrow v1 https://github.com/kleros/escrow/issues/92
- [x] Escrow v2
- [x] Curate v1: https://github.com/kleros/gtcr/issues/333
- [x] Curate v2
- [x] Proof of Humanity v1 https://github.com/Proof-Of-Humanity/proof-of-humanity-web/issues/591
- [x] Proof of Humanity v2
- [x] Dispute Resolver v1 https://github.com/kleros/dispute-resolver/issues/187
- [x] Linguo: won't fix
- [ ] Moderate https://github.com/kleros/kleros-moderate/issues/44
- [x] Tokens list script https://github.com/kleros/t2cr-to-ipfs/issues/9
```

**Comment by salgozino** [comment]
PoH-V2 status:

PoH-V2 already using filebase to store files: https://github.com/Proof-Of-Humanity/proof-of-humanity-v2-web/blob/master/src/app/api/ipfs-upload/route.ts
We don't know which bucket are we using, so I'm creating a new bucket within the main account and asking to Martin to change the env variables in netlify to point to the new poh-v2 bucket.

**Comment by salgozino** [comment]
Curate-V2 status:
As in PoH-V2, curate-v2 is already using Filebase to pin new files according to this function: https://github.com/kleros/curate-v2/blob/master/web/netlify/functions/uploadToIPFS.ts which is called in this util: https://github.com/kleros/curate-v2/blob/971bcb25d7600fceecf5a1b7415785af96fb3c5a/web/src/utils/uploadFileToIPFS.ts#L9C1-L10C1
Cheching to which bucket are we pointing.  My recomendation is to use a specific bucket for curate-v2 as with poh-v2

**Comment by salgozino** [comment]
Escrow-v2:
Same situation as PoH-v2

**Comment by jaybuidl** [comment]
Shared upload endpoint for the v1 apps: https://github.com/kleros/court-functions/issues/11
