### ISSUE TITLE
Node 20 and Yarn 4

### ISSUE THREAD

**Issue by jaybuidl** [kleros/builder-baseline#17]
```[tasklist]
### Tasks
- [ ] https://github.com/kleros/kleros-v2/pull/1419
- [ ] https://github.com/kleros/escrow-v2/pull/18
- [ ] https://github.com/kleros/ui-components-library/pull/56
```
