### ISSUE TITLE
Migration from Goerli to Sepolia

### ISSUE THREAD

**Issue by jaybuidl** [kleros/builder-baseline#19]
```[tasklist]
### Tasks
- [ ] https://github.com/kleros/gtcr/issues/323
- [ ] https://github.com/kleros/ping-pong/issues/1
- [ ] https://github.com/kleros/court/issues/400
- [ ] https://github.com/kleros/gtcr-subgraph/issues/23
- [ ] https://github.com/kleros/centralized-arbitrator-dashboard/issues/48
- [ ] [Kleros Snapshot Module](https://github.com/gnosisguild/zodiac-safe-app): on hold until Snapshot deploys to Sepolia
```

Not maintained
https://github.com/kleros/linguo
https://github.com/kleros/t2cr-ui
